nchains: 100 # Number of chains for BayesianMultiFaultsInversion
chain_length: 50 # Length of each chain for BayesianMultiFaultsInversion
nfaults: 1 # Number of faults
# Set slip sampling mode to 'mag_rake' or 'ss_ds'
slip_sampling_mode: 'mag_rake'
clipping_options:
  enabled: false
  methods:
    - method: 'lon_lat_range'
      lon_lat_range: [86.0, 87.7, 32.5, 33.75] # For 'lon_lat_range' method, in degrees
bounds:
  defaults:
    lon: [Uniform, 78.56, 2.0]
    lat: [Uniform, 41.19, 2.0]
    depth: [Uniform, 5, 20.0]
    dip: [Uniform, 45, 44.9]
    width: [Uniform, 0.1, 29.9]
    length: [Uniform, 5.1, 44.9]
    strike: [Uniform, 180, 180]
    magnitude: [Uniform, 0.0, 10.0]
    rake: [Uniform, -90.0, 180.0]
  fault_1:
    rake: [Uniform, -30, 60.0]
    strike: [Uniform, 0.0, 270.0]
# Set geodata
geodata:
  data: null
  verticals: [true, true]
  polys:
    enabled: true
    boundaries:
      defaults: [Uniform, -200.0, 400.0]
  faults: null # set the fault names for each geodata
  sigmas: # Set the std of the geodata
    update: true
    bounds:
      defaults: [Uniform, -3.0, 6.0]
      sigma_0: [Uniform, -3.0, 6.0]
    values: [0.0, 0.0] # null
    log_scaled: true
data_sources: # Data sources for GPS and InSAR data
  gps:
    directory: '../gps' # Directory containing GPS data files
    file_pattern: 'cogps*' # File pattern to match GPS data files
  insar:
    directory: '../insar/downsample' # Directory containing InSAR data files
    file_pattern: '*.rsp' # File pattern to match InSAR data filess