"""
JiInv slip distribution data converter.

This module handles slip distribution files generated by JiInv (Ji Chen's finite fault inversion program).
JiInv is a widely used earthquake source inversion software that produces slip models from seismic and geodetic data.

JiInv File Format:
==================

Header Section:
- Total number of fault segments: #Total number of fault_segments=     N
- Fault segment definitions with grid parameters:
  Format 1: #Fault_segment =   N nx(Along-strike)=  X Dx=  Y.YYkm ny(downdip)=   Z Dy=  W.WWkm
  Format 2: #Fault_plane =   N followed by #NX=   X DX=  Y.YY NY=   Z DY=  W.WW
- Fault segment boundaries (optional):
  #Boundary of Fault_segment     N
  #Lon.  Lat.  Depth
  (corner coordinates follow)

Data Section:
- Column headers: #Lat. Lon. depth slip rake strike dip t_left t_right (rise_time=t_left+t_right),sliprate,time
- Data format: lat lon depth slip(cm) rake(deg) strike(deg) dip(deg) rupture_time rise_time_start rise_time_end [additional_columns]

Key Features:
- Multi-segment fault geometry support
- Slip values in centimeters
- Rake angles for slip direction
- Temporal rupture parameters (rise time, rupture time)
- Fault patch dimensions from header information

Example JiInv File Structure:
-----------------------------
#Total number of fault_segments=     5
#Fault_segment =   1 nx(Along-strike)=  17 Dx=  5.00km ny(downdip)=   9 Dy=  5.00km
#Boundary of Fault_segment     1
#Lon.  Lat.  Depth
       37.72090       37.93590        1.44184
       36.78270       38.09300        1.44184
       36.81840       38.22540       42.78830
       37.75660       38.06830       42.78830
       37.72090       37.93590        1.44184
#Lat. Lon. depth slip rake strike dip t_left t_right (rise_time=t_left+t_right),sliprate,time
    37.9457    37.7002     3.3212    14.0886    77.3144   282.0000    70.0000     2.4000     2.4000     0.0294    21.1271
    37.9550    37.6444     3.3212     3.5999    -6.2108   282.0000    70.0000     6.4000     0.8000     0.0050    17.6682
    ...

Units and Conventions:
- Coordinates: Decimal degrees (WGS84)
- Depth: Kilometers (positive downward)
- Slip: Centimeters
- Angles: Degrees
- Strike: Clockwise from north (0-360°)
- Dip: Downward from horizontal (0-90°)
- Rake: In fault plane, 0°=left-lateral, 90°=reverse, -90°=normal

References:
- Ji, C., D. J. Wald, and D. V. Helmberger (2002), Source description of the 1999 Hector Mine, 
  California earthquake; Part I: Wavelet domain inversion theory and resolution analysis, 
  Bull. Seismol. Soc. Am., 92, 1192-1207.
"""

from .base_converter import BaseSlipConverter
from .geometry_utils import ReferencePoint, FaultGeometry
import numpy as np
import pandas as pd
from pyproj import Proj
import os
import re


class JiInvSlipConverter(BaseSlipConverter):
    """
    JiInv slip distribution data converter.
    
    Handles JiInv format files with header information about fault geometry
    and converts them to standard formats.
    
    JiInv format includes:
    - Header with fault plane polygons and subfault dimensions  
    - Data columns: Lat Lon depth slip(cm) rake strike dip rupture_time rise_time_start rise_time_end rigidity
    """
    
    def __init__(self, slip_file='jiinv_slip.txt', lon0=None, lat0=None):
        super().__init__(slip_file)
        
        # Set JiInv-specific parameters
        self.reference_point = ReferencePoint.CENTER  # JiInv uses centroid
        self.depth_unit = 'km'
        self.length_unit = 'km'
        self.width_unit = 'km'
        self.converter_type = 'pyproj'
        
        # JiInv-specific attributes
        self.fault_segments = []
        self.df = None
        self.proj = None
        self.utm_zone = None
        
        # Manual projection parameters
        self.manual_lon0 = lon0
        self.manual_lat0 = lat0
    
    def read_slip_file(self):
        """
        Read JiInv slip distribution file with header parsing.
        
        Returns:
            bool: True if successful, False otherwise
        """
        if not os.path.exists(self.input_file):
            print(f"Error: JiInv slip file {self.input_file} not found!")
            return False
        
        try:
            # Parse header and extract fault geometry
            self._parse_header()
            
            # Read data lines
            data_lines = self._extract_data_lines()
            
            # Create DataFrame
            self.df = self._create_dataframe(data_lines)
            
            # Setup projection
            self._setup_projection()
            
            # Convert data to standard format
            self._convert_to_standard_format()
            
            print(f"Loaded {len(self.df)} JiInv fault patches from {len(self.fault_segments)} fault segments")
            print(f"Slip range: {self.df['slip(cm)'].min():.1f} - {self.df['slip(cm)'].max():.1f} cm")
            print(f"Depth range: {self.df['depth'].min():.1f} - {self.df['depth'].max():.1f} km")
            
            return True
            
        except Exception as e:
            print(f"Error reading JiInv file: {e}")
            import traceback
            traceback.print_exc()
            return False
    
    def _parse_header(self):
        """
        Parse JiInv header to extract fault segment information.
        """
        with open(self.input_file, 'r') as f:
            lines = f.readlines()
        
        self.fault_segments = []
        i = 0
        
        while i < len(lines):
            line = lines[i].strip()
            
            # Look for fault plane/segment definitions
            if 'No. of the Fault plane' in line or '#Fault_segment' in line:
                segment = {}
                
                # Extract segment number with safer regex
                if 'No. of the Fault plane' in line:
                    number_matches = re.findall(r'=\s*(\d+)', line)
                    if number_matches:
                        segment['number'] = int(number_matches[0])
                        segment['type'] = 'fault_plane'
                    else:
                        print(f"Warning: Could not parse fault plane number from: {line}")
                        i += 1
                        continue
                        
                elif 'Fault_segment' in line:
                    # Check if this line already contains nx/ny info
                    if 'nx(' in line and 'ny(' in line:
                        # Format: #Fault_segment =   1 nx(Along-strike)=  17 Dx=  5.00km ny(downdip)=   9 Dy=  5.00km
                        number_matches = re.findall(r'Fault_segment\s*=\s*(\d+)', line) # Fault_segment\s*=
                        if number_matches:
                            segment['number'] = int(number_matches[0])
                            segment['type'] = 'fault_segment'
                            
                            nx_match = re.search(r'nx\([^)]+\)=\s*(\d+)', line)
                            dx_match = re.search(r'Dx=\s*([\d.]+)', line)
                            ny_match = re.search(r'ny\([^)]+\)=\s*(\d+)', line)
                            dy_match = re.search(r'Dy=\s*([\d.]+)', line)
                            
                            if all([nx_match, dx_match, ny_match, dy_match]):
                                segment['nx'] = int(nx_match.group(1))
                                segment['dx'] = float(dx_match.group(1))
                                segment['ny'] = int(ny_match.group(1))
                                segment['dy'] = float(dy_match.group(1))
                                self.fault_segments.append(segment)
                            else:
                                print(f"Warning: Could not parse all parameters from: {line}")
                        else:
                            print(f"Warning: Could not parse fault segment number from: {line}")
                        
                        i += 1
                        continue
                    else:
                        number_matches = re.findall(r'Fault_segment\s*(\d+)', line)
                        if number_matches:
                            segment['number'] = int(number_matches[0])
                            segment['type'] = 'fault_segment'
                        else:
                            print(f"Warning: Could not parse fault segment number from: {line}")
                            i += 1
                            continue
                
                # Look for NX/NY line (for fault_plane type or separate segment line)
                i += 1
                found_dimensions = False
                while i < len(lines):
                    current_line = lines[i].strip()
                    
                    if 'NX=' in current_line:
                        # Format: #NX=   7 DX=  9.00 NY=   7 DY=  3.00
                        numbers = re.findall(r'=\s*([\d.]+)', current_line)
                        if len(numbers) >= 4:
                            segment['nx'] = int(float(numbers[0]))
                            segment['dx'] = float(numbers[1])
                            segment['ny'] = int(float(numbers[2]))
                            segment['dy'] = float(numbers[3])
                            found_dimensions = True
                        else:
                            print(f"Warning: Could not parse NX/NY line: {current_line}")
                        break
                    elif current_line.startswith('#Lat.') or current_line.startswith('Lat.'):
                        # Reached data header, stop looking for NX/NY
                        break
                    elif current_line.startswith('#No. of the Fault plane') or current_line.startswith('#Fault_segment'):
                        # Found next segment, back up one line
                        i -= 1
                        break
                    
                    i += 1
                
                # Only add segment if we found dimension info
                if found_dimensions and 'nx' in segment and 'ny' in segment:
                    self.fault_segments.append(segment)
                elif 'nx' not in segment:
                    print(f"Warning: No dimensions found for segment {segment.get('number', 'unknown')}")
            
            i += 1
        
        print(f"Found {len(self.fault_segments)} fault segments:")
        for seg in self.fault_segments:
            print(f"  Segment {seg['number']} ({seg['type']}): {seg['nx']}x{seg['ny']} patches, {seg['dx']}x{seg['dy']} km")
    
    def _extract_data_lines(self):
        """
        Extract data lines from JiInv file.
        """
        with open(self.input_file, 'r') as f:
            lines = f.readlines()
        
        data_lines = []
        for line in lines:
            line = line.strip()
            # Skip comments and empty lines
            if line.startswith('#') or not line:
                continue
            
            # Check if line contains numeric data (lat, lon, depth...)
            parts = line.split()
            if len(parts) >= 7:  # Minimum required columns
                try:
                    # Try to parse first few values as numbers
                    float(parts[0])  # lat
                    float(parts[1])  # lon
                    float(parts[2])  # depth
                    data_lines.append(line)
                except ValueError:
                    continue
        
        return data_lines
    
    def _create_dataframe(self, data_lines):
        """
        Create DataFrame from data lines.
        """
        # Parse data lines
        data = []
        for line in data_lines:
            parts = line.split()
            if len(parts) >= 10:  # Standard JiInv format
                data.append([
                    float(parts[0]),  # lat
                    float(parts[1]),  # lon
                    float(parts[2]),  # depth
                    float(parts[3]),  # slip(cm)
                    float(parts[4]),  # rake
                    float(parts[5]),  # strike
                    float(parts[6]),  # dip
                    float(parts[7]),  # rupture_time
                    float(parts[8]),  # rise_time_start
                    float(parts[9])   # rise_time_end
                ])
        
        columns = ['lat', 'lon', 'depth', 'slip(cm)', 'rake', 'strike', 'dip', 
                  'rupture_time', 'rise_time_start', 'rise_time_end']
        
        return pd.DataFrame(data, columns=columns)
    
    def _setup_projection(self):
        """
        Setup UTM projection and fault geometry calculator.
        """
        if self.df is not None and len(self.df) > 0:
            # Determine projection parameters
            if self.manual_lon0 is not None and self.manual_lat0 is not None:
                lon0, lat0 = self.manual_lon0, self.manual_lat0
                print(f"Using manual projection parameters: lon0={lon0:.4f}, lat0={lat0:.4f}")
            else:
                # Use data center as projection origin
                lon0 = self.df['lon'].mean()
                lat0 = self.df['lat'].mean()
                print(f"Using data center as projection origin: lon0={lon0:.4f}, lat0={lat0:.4f}")
            
            # Setup UTM projection
            self.utm_zone = int((lon0 + 180) // 6) + 1
            self.proj = Proj(proj='utm', zone=self.utm_zone, ellps='WGS84')
            self.fault_geometry = FaultGeometry(self.proj)
            
            print(f"Using UTM zone: {self.utm_zone}")
    
    def _convert_to_standard_format(self):
        """
        Convert JiInv data to standard slip_data format.
        """
        # Convert rake to strike-slip and dip-slip components
        rake_rad = np.deg2rad(self.df['rake'].values)
        slip_total_cm = self.df['slip(cm)'].values
        slip_total_m = slip_total_cm / 100.0  # Convert cm to m
        
        strike_slip = slip_total_m * np.cos(rake_rad)
        dip_slip = slip_total_m * np.sin(rake_rad)
        
        # Estimate patch dimensions from fault segments
        length_km, width_km = self._estimate_patch_dimensions()
        
        # Populate standard slip_data format
        self.slip_data = {
            'longitude': self.df['lon'].values,
            'latitude': self.df['lat'].values,
            'depth': self.df['depth'].values,
            'length': length_km,
            'width': width_km,
            'strike': self.df['strike'].values,
            'dip': self.df['dip'].values,
            'strike_slip': strike_slip,
            'dip_slip': dip_slip,
            'total_slip': slip_total_m
        }
    
    def _estimate_patch_dimensions(self):
        """
        Estimate patch dimensions based on fault segment information.
        """
        if not self.fault_segments:
            # Default values if no header info
            print("Warning: No fault segment info found, using default patch size")
            return np.full(len(self.df), 5.0), np.full(len(self.df), 3.0)
        
        # Create arrays for patch dimensions
        length_km = np.zeros(len(self.df))
        width_km = np.zeros(len(self.df))
        
        # Assign patches to segments based on spatial clustering or order
        patches_per_segment = []
        for segment in self.fault_segments:
            if 'nx' in segment and 'ny' in segment:
                patches_per_segment.append(segment['nx'] * segment['ny'])
            else:
                patches_per_segment.append(0)
        
        # Assign dimensions to patches
        patch_idx = 0
        for i, segment in enumerate(self.fault_segments):
            n_patches = patches_per_segment[i]
            if n_patches > 0 and patch_idx + n_patches <= len(self.df):
                dx = segment.get('dx', 5.0)
                dy = segment.get('dy', 3.0)
                length_km[patch_idx:patch_idx + n_patches] = dx
                width_km[patch_idx:patch_idx + n_patches] = dy
                patch_idx += n_patches
        
        # Fill remaining patches with default values
        if patch_idx < len(self.df):
            length_km[patch_idx:] = 5.0
            width_km[patch_idx:] = 3.0
        
        return length_km, width_km
    
    def write_gmt_files_by_segment(self, output_prefix="jiinv_segment"):
        """
        Write separate GMT files for each fault segment.
        
        Args:
            output_prefix (str): Prefix for output files
            
        Returns:
            list: List of output filenames
        """
        if self.slip_data is None:
            print("Error: No data loaded. Call read_slip_file() first.")
            return []
        
        if not self.fault_segments:
            print("Warning: No fault segment information available.")
            return []
        
        output_files = []
        patch_idx = 0
        
        try:
            for i, segment in enumerate(self.fault_segments):
                n_patches = segment.get('nx', 0) * segment.get('ny', 0)
                if n_patches == 0:
                    continue
                
                # Extract patches for this segment
                end_idx = min(patch_idx + n_patches, len(self.slip_data['longitude']))
                
                if patch_idx >= end_idx:
                    break
                
                # Create output filename
                segment_num = segment.get('number', i+1)
                segment_type = segment.get('type', 'segment')
                output_file = f"{output_prefix}_{segment_type}_{segment_num:02d}.gmt"
                
                # Write GMT file for this segment
                with open(output_file, 'w') as fout:
                    for j in range(patch_idx, end_idx):
                        # Get slip values
                        strike_slip = self.slip_data['strike_slip'][j]
                        dip_slip = self.slip_data['dip_slip'][j]
                        total_slip = self.slip_data['total_slip'][j]
                        
                        # Calculate patch corners
                        corners = self.calculate_patch_corners(
                            self.slip_data['longitude'][j],
                            self.slip_data['latitude'][j],
                            self.slip_data['depth'][j],
                            self.slip_data['length'][j],
                            self.slip_data['width'][j],
                            self.slip_data['strike'][j],
                            self.slip_data['dip'][j]
                        )
                        
                        # Write GMT segment header
                        fout.write(f"> -Z{total_slip:.6f} # {strike_slip:.6f} {-dip_slip:.6f} 0.0\n")
                        
                        # Write corner coordinates
                        for corner in corners:
                            lon_corner, lat_corner, depth_corner = corner
                            fout.write(f"{lon_corner:.6f} {lat_corner:.6f} {depth_corner:.3f}\n")
                
                output_files.append(output_file)
                patch_idx = end_idx
                
                print(f"Segment {segment_num} ({segment_type}): {end_idx-patch_idx+n_patches} patches -> {output_file}")
        
        except Exception as e:
            print(f"Error writing segment GMT files: {e}")
            return []
        
        print(f"Successfully wrote {len(output_files)} segment GMT files")
        return output_files
    
    def get_segment_statistics(self):
        """
        Get statistics for each fault segment.
        
        Returns:
            list: List of segment statistics
        """
        if self.slip_data is None or not self.fault_segments:
            return []
        
        segment_stats = []
        patch_idx = 0
        
        for i, segment in enumerate(self.fault_segments):
            n_patches = segment.get('nx', 0) * segment.get('ny', 0)
            if n_patches == 0:
                continue
            
            end_idx = min(patch_idx + n_patches, len(self.slip_data['longitude']))
            
            if patch_idx >= end_idx:
                break
            
            # Extract data for this segment
            segment_slip = self.slip_data['total_slip'][patch_idx:end_idx]
            segment_depth = self.slip_data['depth'][patch_idx:end_idx]
            segment_lon = self.slip_data['longitude'][patch_idx:end_idx]
            segment_lat = self.slip_data['latitude'][patch_idx:end_idx]
            
            stats = {
                'segment_number': segment.get('number', i+1),
                'segment_type': segment.get('type', 'segment'),
                'n_patches': end_idx - patch_idx,
                'nx': segment.get('nx', 0),
                'ny': segment.get('ny', 0),
                'dx_km': segment.get('dx', 0),
                'dy_km': segment.get('dy', 0),
                'slip_min_m': np.min(segment_slip),
                'slip_max_m': np.max(segment_slip),
                'slip_mean_m': np.mean(segment_slip),
                'depth_min_km': np.min(segment_depth),
                'depth_max_km': np.max(segment_depth),
                'lon_range': [np.min(segment_lon), np.max(segment_lon)],
                'lat_range': [np.min(segment_lat), np.max(segment_lat)],
                'total_moment': np.sum(segment_slip) * segment.get('dx', 5) * segment.get('dy', 3) * 1e9 * 3e10  # Rough estimate
            }
            
            segment_stats.append(stats)
            patch_idx = end_idx
        
        return segment_stats
    
    def print_segment_statistics(self):
        """
        Print detailed statistics for each fault segment.
        """
        stats = self.get_segment_statistics()
        
        if not stats:
            print("No segment statistics available.")
            return
        
        print("\n" + "="*80)
        print("FAULT SEGMENT STATISTICS")
        print("="*80)
        
        for stat in stats:
            print(f"\nSegment {stat['segment_number']} ({stat['segment_type']}):")
            print(f"  Grid: {stat['nx']}×{stat['ny']} patches ({stat['n_patches']} total)")
            print(f"  Patch size: {stat['dx_km']:.1f}×{stat['dy_km']:.1f} km")
            print(f"  Slip range: {stat['slip_min_m']:.3f} - {stat['slip_max_m']:.3f} m (mean: {stat['slip_mean_m']:.3f} m)")
            print(f"  Depth range: {stat['depth_min_km']:.1f} - {stat['depth_max_km']:.1f} km")
            print(f"  Longitude: {stat['lon_range'][0]:.4f}° - {stat['lon_range'][1]:.4f}°")
            print(f"  Latitude: {stat['lat_range'][0]:.4f}° - {stat['lat_range'][1]:.4f}°")
            print(f"  Estimated moment: {stat['total_moment']:.2e} N*m")
    
    def convert_by_segments(self, output_prefix="jiinv_segment", fig_file="jiinv_3d_plot.png"):
        """
        Convert slip data and output separate files for each segment.
        
        Args:
            output_prefix (str): Prefix for output files
            
        Returns:
            bool: True if successful
        """
        if not self.read_slip_file():
            return False
        
        # Print segment statistics
        self.print_segment_statistics()
        
        # Write GMT files by segment
        gmt_files = self.write_gmt_files_by_segment(output_prefix)
        
        # Write combined GMT file
        combined_gmt = f"{output_prefix}_combined.gmt"
        if self.write_gmt_file(combined_gmt):
            print(f"Combined GMT file: {combined_gmt}")
        
        # Write summary file
        summary_file = f"{output_prefix}_summary.txt"
        self._write_segment_summary(summary_file)

        print(f"\nCreating 3D visualization...")
        if not self.plot_3d(save_fig=True, output_file=fig_file):
            return False
        
        return len(gmt_files) > 0
    
    def _write_segment_summary(self, output_file):
        """
        Write segment summary to file.
        """
        stats = self.get_segment_statistics()
        
        try:
            with open(output_file, 'w') as f:
                f.write("JiInv Fault Segment Summary\n")
                f.write("="*50 + "\n\n")
                f.write(f"Total fault segments: {len(stats)}\n")
                f.write(f"Total patches: {sum(s['n_patches'] for s in stats)}\n\n")
                
                for stat in stats:
                    f.write(f"Segment {stat['segment_number']} ({stat['segment_type']}):\n")
                    f.write(f"  Grid: {stat['nx']}x{stat['ny']} = {stat['n_patches']} patches\n")
                    f.write(f"  Patch size: {stat['dx_km']:.1f}x{stat['dy_km']:.1f} km\n")
                    f.write(f"  Slip: {stat['slip_min_m']:.3f}-{stat['slip_max_m']:.3f} m (avg: {stat['slip_mean_m']:.3f} m)\n")
                    f.write(f"  Depth: {stat['depth_min_km']:.1f}-{stat['depth_max_km']:.1f} km\n")
                    f.write(f"  Location: {stat['lon_range'][0]:.4f}-{stat['lon_range'][1]:.4f}°E, ")
                    f.write(f"{stat['lat_range'][0]:.4f}-{stat['lat_range'][1]:.4f}°N\n\n")
                    # f.write(f"  Moment: {stat['total_moment']:.2e} N*m\n\n")
            
            print(f"Segment summary written to: {output_file}")
            
        except Exception as e:
            print(f"Error writing segment summary: {e}")
    

def main():
    """
    Main function to demonstrate the JiInv slip converter usage.
    """
    import argparse
    
    parser = argparse.ArgumentParser(description='Convert JiInv slip distribution files')
    parser.add_argument('input_file', help='Input JiInv slip file')
    parser.add_argument('--lon0', type=float, help='Manual longitude origin')
    parser.add_argument('--lat0', type=float, help='Manual latitude origin')
    parser.add_argument('--by-segments', action='store_true', 
                        help='Output separate files for each fault segment')
    parser.add_argument('--output-prefix', default='jiinv', 
                        help='Output file prefix (default: jiinv)')
    
    args = parser.parse_args()
    
    # Create converter
    converter = JiInvSlipConverter(args.input_file, args.lon0, args.lat0)
    
    if args.by_segments:
        # Convert by segments
        converter.convert_by_segments(args.output_prefix)
    else:
        # Standard conversion
        converter.convert_all()
    
    
if __name__ == "__main__":
    main()


# def main():
#     """
#     Main function to demonstrate the JiInv slip converter usage.
#     """
#     # Example usage with automatic projection
#     converter = JiInvSlipConverter('jiinv_slip.txt')
    
#     # Example with manual projection parameters
#     # converter = JiInvSlipConverter('jiinv_slip.txt', lon0=37.0, lat0=38.0)
    
#     converter.convert_all()


# if __name__ == "__main__":
#     main()