"""
Mudpy slip distribution data converter.
Handles Mudpy format files from Diego Melgar and converts them to standard formats.
"""

from .base_converter import BaseSlipConverter
from .geometry_utils import ReferencePoint, FaultGeometry
import numpy as np
import pandas as pd
from pyproj import Proj
import os


class MudpySlipConverter(BaseSlipConverter):
    """
    Mudpy slip distribution data converter.

    Handles slip distribution files generated by Diego Melgar's Mudpy program.
    Format: No, lon, lat, z(km), strike, dip, ss-slip(m), ds-slip(m), ss_len(m), ds_len(m)
    """

    def __init__(self, slip_file='mudpy_slip.txt'):
        super().__init__(slip_file)

        # Set Mudpy-specific parameters
        self.reference_point = ReferencePoint.CENTER
        self.depth_unit = 'km'
        self.length_unit = 'm'  # Mudpy uses meters
        self.width_unit = 'm'
        self.converter_type = 'pyproj'

        # Mudpy-specific attributes
        self.df = None
        self.proj = None
        self.utm_zone = None
        
        # Define expected columns
        self.core_columns = ['No', 'lon', 'lat', 'z_km', 'strike', 'dip', 
                           'ss_slip_m', 'ds_slip_m', 'ss_len_m', 'ds_len_m']

    def read_mesh_file(self, mesh_file=None):
        """
        Read mesh file containing corner coordinates.
        
        Args:
            mesh_file (str): Path to mesh file
            
        Returns:
            bool: True if successful, False otherwise
        """
        if mesh_file is None:
            # Try to find mesh file based on slip file name
            base_name = os.path.splitext(self.input_file)[0]
            mesh_file = f"{base_name}_mesh.txt"
        
        if not os.path.exists(mesh_file):
            print(f"Mesh file {mesh_file} not found, will use calculated corners")
            return False
        
        try:
            from scipy.spatial import KDTree
            
            # Read mesh file
            mesh_data = []
            with open(mesh_file, 'r') as f:
                for line in f:
                    line = line.strip()
                    if line.startswith('#') or not line:
                        continue
                    
                    # Parse mesh data
                    parts = line.split()
                    if len(parts) >= 14:
                        fault_no = int(float(parts[0]))
                        
                        # Centroid
                        cent_lon = float(parts[1])
                        cent_lat = float(parts[2])
                        cent_z = float(parts[3])
                        # Node 1
                        node1_lon = float(parts[4])
                        node1_lat = float(parts[5])
                        node1_z = float(parts[6])
                        # Node 2
                        node2_lon = float(parts[7])
                        node2_lat = float(parts[8])
                        node2_z = float(parts[9])
                        # Node 3
                        node3_lon = float(parts[10])
                        node3_lat = float(parts[11])
                        node3_z = float(parts[12])

                        # Store corners for this patch
                        corners = [
                            (node1_lon, node1_lat, abs(node1_z)),
                            (node2_lon, node2_lat, abs(node2_z)),
                            (node3_lon, node3_lat, abs(node3_z)),
                        ]
                        
                        centroid = (# cent_lon, cent_lat, abs(cent_z))
                            np.mean([node1_lon, node2_lon, node3_lon]),
                            np.mean([node1_lat, node2_lat, node3_lat]),
                            np.mean([abs(node1_z), abs(node2_z), abs(node3_z)])
                        )
                        
                        mesh_data.append({
                            'fault_no': fault_no,
                            'centroid': centroid,
                            'corners': corners
                        })
            
            # Store mesh data
            self.mesh_corners = {item['fault_no']: item['corners'] for item in mesh_data}
            
            # Build KDTree for fast searching
            centroids = np.array([item['centroid'] for item in mesh_data])
            self.mesh_centroids = centroids
            self.mesh_fault_nos = [item['fault_no'] for item in mesh_data]
            
            # Apply weights for different units (degrees vs km)
            weights = np.array([1.0, 1.0, 0.01])  # lon, lat, depth weights
            weighted_centroids = centroids * weights
            
            self.mesh_kdtree = KDTree(weighted_centroids)
            
            print(f"Loaded corner data for {len(self.mesh_corners)} patches from mesh file")
            print(f"Built KDTree for fast mesh corner lookup")
            return True
            
        except Exception as e:
            print(f"Error reading mesh file: {e}")
            return False
    
    def calculate_patch_corners(self, lon, lat, depth, length, width, strike, dip):
        """
        Calculate the four corner points of a rectangular fault patch.
        
        For Mudpy, if mesh file is available, use actual corners from mesh file.
        Otherwise, fall back to geometric calculation.
        
        Args:
            lon (float): Longitude of fault reference point (degrees)
            lat (float): Latitude of fault reference point (degrees)
            depth (float): Depth of fault reference point (positive downward)
            length (float): Fault length along strike
            width (float): Fault width along dip
            strike (float): Strike angle (degrees)
            dip (float): Dip angle (degrees)
            
        Returns:
            list: Four corner points as [(lon1, lat1, depth1), ...]
        """
        # Try to use mesh corners if available
        if hasattr(self, 'mesh_corners') and self.mesh_corners and hasattr(self, 'mesh_kdtree'):
            # Use KDTree for fast nearest neighbor search
            target = np.array([lon, lat, depth/100.0])  # Remove extra brackets
            
            # Find the closest centroid
            distances, indices = self.mesh_kdtree.query(target, k=1)
            
            # Handle both scalar and array returns
            if np.isscalar(indices):
                closest_idx = indices
                closest_distance = distances
            else:
                closest_idx = indices[0] if len(indices.shape) > 0 else indices
                closest_distance = distances[0] if len(distances.shape) > 0 else distances
            
            # Use a reasonable threshold
            # print(lon, lat, depth, "Closest mesh corner index:", closest_idx, "Distance:", closest_distance)
            # print(f"Closest mesh corner: {self.mesh_corners[self.mesh_fault_nos[closest_idx]]}")
            # print(f"Closest mesh fault centroid: {self.mesh_centroids[closest_idx]}")
            if closest_distance < 0.01:  # Approximately 1km tolerance
                fault_no = self.mesh_fault_nos[closest_idx]
                return self.mesh_corners[fault_no]
        
        # Fallback to geometric calculation
        if self.fault_geometry is None:
            raise ValueError("Fault geometry not initialized and no mesh corners available.")
        
        return self.fault_geometry.calculate_fault_corners(
            lon, lat, depth, length, width, strike, dip,
            reference_point=self.reference_point,
            depth_unit=self.depth_unit,
            length_unit=self.length_unit,
            width_unit=self.width_unit,
            converter_type=self.converter_type
        )

    def read_slip_file(self):
        """
        Read Mudpy slip distribution file with flexible column detection.
        
        Returns:
            bool: True if successful, False otherwise
        """
        if not os.path.exists(self.input_file):
            print(f"Error: Mudpy slip file {self.input_file} not found!")
            return False
        
        try:
            # First try to read mesh file for corner coordinates
            self.read_mesh_file()

            # Read header separately to detect column names
            header_columns = None
            data_start_line = 0
            
            with open(self.input_file, 'r') as f:
                for i, line in enumerate(f):
                    line = line.strip()
                    if line.startswith('#') and any(keyword in line.lower() for keyword in ['lon', 'lat', 'strike', 'dip', 'slip']):
                        # Found header line - parse comma-separated column names
                        header_line = line[1:].strip()  # Remove # and whitespace
                        header_columns = [col.strip() for col in header_line.split(',')]
                        data_start_line = i + 1
                        break
                    elif not line.startswith('#') and line:
                        # Found first data line without header
                        data_start_line = i
                        break
            
            # Read data (skip header lines, use whitespace separation)
            df = pd.read_csv(self.input_file, sep=r'\s+', skiprows=data_start_line, header=None)
            
            # Create standardized dataframe
            self.df = pd.DataFrame()
            
            if header_columns:
                # Map columns by name from header
                print(f"Detected header columns: {header_columns}")
                col_mapping = self._map_columns_by_name(header_columns)
                print(col_mapping)
                for i, (std_name, (header_name, col_index)) in enumerate(col_mapping.items()):
                    if i < len(df.columns):
                        self.df[std_name] = df.iloc[:, col_index]
            else:
                # Map columns by position (fallback)
                print("No header detected, using position-based mapping")
                n_cols = len(df.columns)
                
                if n_cols == 10:  # Simple format
                    for i, col_name in enumerate(self.core_columns):
                        self.df[col_name] = df.iloc[:, i]
                elif n_cols == 13 or n_cols == 14:  # Standard format with rise,dura,rupt_time,rigidity
                    col_indices = [0, 1, 2, 3, 4, 5, 8, 9, 10, 11]  # Skip indices 6,7,12,13
                    for i, col_name in enumerate(self.core_columns):
                        if i < len(col_indices):
                            self.df[col_name] = df.iloc[:, col_indices[i]]
                else:
                    raise ValueError(f"Unexpected Mudpy file format with {n_cols} columns")
                
            print(self.df.head())
            
            # Validate required columns
            required_cols = ['lon', 'lat', 'z_km', 'strike', 'dip', 'ss_slip_m', 'ds_slip_m']
            missing_cols = [col for col in required_cols if col not in self.df.columns]
            if missing_cols:
                raise ValueError(f"Missing required columns: {missing_cols}")
            
            # Setup projection (only if no mesh corners available)
            if not hasattr(self, 'mesh_corners') or not self.mesh_corners:
                self._setup_projection()
            
            # # Process data - convert length/width from meters to kilometers
            # length_km = self.df.get('ss_len_m', pd.Series([5000.0] * len(self.df))).values / 1000.0
            # width_km = self.df.get('ds_len_m', pd.Series([3000.0] * len(self.df))).values / 1000.0
            length_m = self.df['ss_len_m'].values
            width_m = self.df['ds_len_m'].values
            
            # Calculate total slip
            ss_slip = self.df['ss_slip_m'].values
            ds_slip = self.df['ds_slip_m'].values
            total_slip = np.sqrt(ss_slip**2 + ds_slip**2)
            
            # Populate standard slip_data format
            self.slip_data = {
                'longitude': self.df['lon'].values,
                'latitude': self.df['lat'].values,
                'depth': self.df['z_km'].values,
                'length': length_m,
                'width': width_m,
                'strike': self.df['strike'].values,
                'dip': self.df['dip'].values,
                'strike_slip': ss_slip,
                'dip_slip': ds_slip,
                'total_slip': total_slip,
            }
    
            print(f"Loaded {len(self.df)} Mudpy fault patches")
            print(f"Slip range: {total_slip.min():.3f} - {total_slip.max():.3f} m")
            if hasattr(self, 'mesh_corners') and self.mesh_corners:
                print(f"Using mesh corner coordinates for {len(self.mesh_corners)} patches")
            
            return True
            
        except Exception as e:
            print(f"Error reading Mudpy file: {e}")
            import traceback
            traceback.print_exc()
            return False
    
    def _map_columns_by_name(self, header_columns):
        """
        Map header column names to standard names.
        
        Args:
            header_columns: List of column names from header (comma-separated)
            
        Returns:
            dict: Mapping from standard names to header column names (in order)
        """
        mapping = {}
        
        # Convert to lowercase for comparison
        cols_lower = [col.lower().strip() for col in header_columns]
        
        # Define mapping patterns
        patterns = {
            'No': ['no', 'num', 'index', 'id', '#no'],
            'lon': ['lon', 'longitude', 'long'],
            'lat': ['lat', 'latitude'],
            'z_km': ['z', 'depth', 'z(km)', 'z_km', 'dep'],
            'strike': ['strike', 'str'],
            'dip': ['dip'],
            'ss_slip_m': ['ss-slip', 'ss_slip', 'sstrike', 'strike_slip', 'ss-slip(m)'],
            'ds_slip_m': ['ds-slip', 'ds_slip', 'ddip', 'dip_slip', 'ds-slip(m)'],
            'ss_len_m': ['ss_len', 'ss-len', 'length', 'ss_len(m)', 'ss_length'],
            'ds_len_m': ['ds_len', 'ds-len', 'width', 'ds_len(m)', 'ds_width']
        }
        
        for std_name, possible_names in patterns.items():
            for i, col_lower in enumerate(cols_lower):
                if any(pattern in col_lower for pattern in possible_names):
                    mapping[std_name] = (header_columns[i], i)  # Store original name and index
                    break
        
        return mapping
    
    def _setup_projection(self):
        """
        Setup UTM projection and fault geometry calculator.
        """
        if self.df is not None and len(self.df) > 0:
            lat_ref, lon_ref = self.df.iloc[0]['lat'], self.df.iloc[0]['lon']
            self.utm_zone = int((lon_ref + 180) // 6) + 1
            self.proj = Proj(proj='utm', zone=self.utm_zone, ellps='WGS84')
            self.fault_geometry = FaultGeometry(self.proj)
            
            print(f"Using UTM zone: {self.utm_zone}")
            print(f"Reference point: ({lat_ref:.4f}°, {lon_ref:.4f}°)")


def main():
    """
    Main function to demonstrate the Mudpy slip converter usage.
    """
    converter = MudpySlipConverter('mudpy_slip.txt')
    converter.convert_all()


if __name__ == "__main__":
    main()