nchains: 100 # Number of chains for BayesianMultiFaultsInversion
chain_length: 50 # Length of each chain for BayesianMultiFaultsInversion
nfaults: 1 # Number of faults
lon_lat_0: null # UTM coordinates of the origin
# Set slip sampling mode to 'mag_rake' or 'ss_ds'
slip_sampling_mode: 'mag_rake'
clipping_options:
  enabled: false
  methods:
    - method: 'lon_lat_range'
      lon_lat_range: [86.0, 87.7, 32.5, 33.75] # For 'lon_lat_range' method
bounds:
  defaults:
    lon: ['Uniform', 119, 5.0]
    lat: ['Uniform', 21, 5.0]
    depth: ['Uniform', 0, 50]
    dip: ['Uniform', 45, 44.9]
    width: ['Uniform', 5.1, 39.9]
    length: ['Uniform', 5.1, 74.9]
    strike: ['Uniform', 0, 360]
    magnitude: ['Uniform', 0, 10]
    rake: ['Uniform', 60, 60]
  fault_1:
    rake: [Uniform, -30, 60.0]
    strike: [Uniform, 0.0, 270.0]
fixed_params:
  # fault_0:
    # lon: 102.205
    # depth: 3.1578
  fault_1:
    lon: -117.541
    lat: 35.6431
    depth: 0.0
    strike: 227.0
geodata:
  data: null
  verticals: false # Set the verticals for each geodata
  polys:
    enabled: true
    boundaries:
      defaults: [Uniform, -200.0, 400.0]
  faults: null # set the fault names for each geodata
  sigmas: # Set the unit weight standard deviations for each geodata
    update: true
    bounds:
      defaults: [Uniform, -3.0, 6.0]
      sigma_0: [Uniform, -3.0, 6.0]
    values: [0.0, 0.0, 0.0, 0.0] # null
    log_scaled: true
data_sources: # Data sources for GPS and InSAR data
  gps:
    directory: '../gps' # Directory containing GPS data files
    file_pattern: 'cogps*' # File pattern to match GPS data files
  insar:
    directory: '../insar/downsample' # Directory containing InSAR data files
    file_pattern: '*.rsp' # File pattern to match InSAR data filess