"""
Utilities for geodetic data downsampling workflows.

This package is intentionally lightweight: configuration normalization and
validation can be imported without a working CSI installation. Processing
functions that need CSI live in the CLI layer for now.
"""

from .config import (
    AMPLITUDE_STAT_CHOICES,
    DEFAULT_OPTICAL_CONFIG,
    DEFAULT_SAR_CONFIG,
    DEFAULT_PHASE_CYCLE_CORRECTION,
    COVAR_MISSING_POLICY_CHOICES,
    DEFAULT_PROCESSING_REGION,
    DOWNSAMPLE_METHOD_CHOICES,
    FOCUS_REGION_COORD_CHOICES,
    FAULT_MODEL_GEOMETRY_CHOICES,
    FAULT_MODEL_TYPE_CHOICES,
    FAULT_MODEL_USE_CHOICES,
    FAULT_PLOT_STAGE_CHOICES,
    ORIGIN_MODE_CHOICES,
    PROCESSING_REGION_GEOMETRY_CHOICES,
    SAR_MODE_CHOICES,
    SAR_READER_ALIASES,
    SAR_OUTPUT_SUFFIX_BY_MODE,
    SAR_READER_CHOICES,
    SPLIT_METRIC_CHOICES,
    compact_kwargs,
    deep_update,
    get_sar_output_name,
    normalize_downsample_config,
    normalize_optical_config,
    normalize_sar_config,
    validate_optical_config,
    validate_downsample_config,
    validate_sar_config,
)
from .grid_template import (
    RSP_GEOMETRY_CHOICES,
    RspGridTemplate,
    apply_rsp_grid_template,
    read_rsp_grid_template,
)
from .plotting import plot_decimated_geodata
from .processing_region import (
    apply_processing_region,
    format_processing_region_report,
    processing_region_report_file,
)
from .observation_correction import (
    apply_observation_correction,
    correction_fit_mask,
    format_observation_correction_report,
    observation_correction_report_file,
)
from .phase_cycle_correction import (
    apply_phase_cycle_correction,
    format_phase_cycle_correction_report,
    phase_cycle_correction_report_file,
)
from .observation_grid import (
    OBSERVATION_GRID_SCHEMA_VERSION,
    ObservationGrid,
    ObservationVariable,
    build_observation_grid,
    export_observation_grid,
    format_observation_export_report,
    observation_export_report_file,
    read_observation_grid,
    resolve_observation_variable,
    write_observation_geotiffs,
    write_observation_netcdf,
)
from .varres_io import (
    CsiVarresResult,
    VARRES_DATA_TYPES,
    read_csi_varres_result,
)

__all__ = [
    "DEFAULT_SAR_CONFIG",
    "DEFAULT_OPTICAL_CONFIG",
    "DEFAULT_PHASE_CYCLE_CORRECTION",
    "AMPLITUDE_STAT_CHOICES",
    "COVAR_MISSING_POLICY_CHOICES",
    "DEFAULT_PROCESSING_REGION",
    "DOWNSAMPLE_METHOD_CHOICES",
    "FOCUS_REGION_COORD_CHOICES",
    "FAULT_MODEL_GEOMETRY_CHOICES",
    "FAULT_MODEL_TYPE_CHOICES",
    "FAULT_MODEL_USE_CHOICES",
    "FAULT_PLOT_STAGE_CHOICES",
    "ORIGIN_MODE_CHOICES",
    "PROCESSING_REGION_GEOMETRY_CHOICES",
    "RSP_GEOMETRY_CHOICES",
    "SAR_MODE_CHOICES",
    "SAR_READER_ALIASES",
    "SAR_OUTPUT_SUFFIX_BY_MODE",
    "SAR_READER_CHOICES",
    "SPLIT_METRIC_CHOICES",
    "RspGridTemplate",
    "apply_processing_region",
    "apply_rsp_grid_template",
    "compact_kwargs",
    "deep_update",
    "format_processing_region_report",
    "get_sar_output_name",
    "normalize_downsample_config",
    "normalize_optical_config",
    "normalize_sar_config",
    "processing_region_report_file",
    "ObservationGrid",
    "ObservationVariable",
    "OBSERVATION_GRID_SCHEMA_VERSION",
    "CsiVarresResult",
    "VARRES_DATA_TYPES",
    "apply_observation_correction",
    "apply_phase_cycle_correction",
    "build_observation_grid",
    "correction_fit_mask",
    "export_observation_grid",
    "format_observation_correction_report",
    "format_phase_cycle_correction_report",
    "format_observation_export_report",
    "observation_correction_report_file",
    "phase_cycle_correction_report_file",
    "observation_export_report_file",
    "read_observation_grid",
    "resolve_observation_variable",
    "read_csi_varres_result",
    "write_observation_geotiffs",
    "write_observation_netcdf",
    "read_rsp_grid_template",
    "validate_downsample_config",
    "validate_optical_config",
    "validate_sar_config",
    "plot_decimated_geodata",
]
